baseURL = "https://www.ahmedalhulaibi.com/"
languageCode = "en-us"
title = "Ahmed Al-Hulaibi"
theme = "hugo-coder"

publishDir = "docs"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Ahmed Al-Hulaibi"
    info = "Back-End Software Engineer"
    description = "Ahmed Al-Hulaibi's personal website"
    keywords = "blog,developer,personal"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/ahmedalhulaibi/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/ahmedalhulaibi/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/ahmedhulaibi/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url  = "/projects/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"